# Generated by Django 3.2.16 on 2024-12-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='tag',
            new_name='tags',
        ),
    ]
