# Generated by Django 3.2.16 on 2024-12-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_tag_recipetag_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='tags',
            new_name='tag',
        ),
    ]
