# Generated by Django 3.2.16 on 2024-12-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20241213_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
