# Generated by Django 3.2.16 on 2024-12-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipeingredient_unique_recipe_ingredient'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_recipe_ingredient',
        ),
    ]
